Fix GCC build issue with ambiguous for loop iterator
Previous code would raise this error with GCC 5.5.0:
build/obj/scenario/monster.cpp:804:19: error: use of 'abil' before deduction of 'auto'
  for(auto& abil : abil) {
                   ^

I'd advise to do some further refactoring to prevent confusion between the public 'abil'
which is a map of two types of abilities, and the various local 'abil's that shadow it
in monster.cpp.